import type { DashboardKpis, Employee, JobDepartmentHistory, Loan, LoanRepayment, SalaryHistory } from "@/types/domain";

export const mockEmployees: Employee[] = [
  {
    id: "emp-1",
    employee_code: "0000000001",
    full_name: "Ana Torres",
    first_name: "Ana",
    last_name: "Torres",
    email: "ana.torres@linguameeting.com",
    phone: "+1-555-0101",
    nationality: "ES",
    residence_country: "ES",
    legal_name_bank: null,
    identity_document: null,
    address_line: null,
    address_country: null,
    address_city: null,
    address_postal_code: null,
    bank_name: null,
    bank_account_number: "ES90 2100 0418 4502 0005 1332",
    swift_bic: null,
    bank_route_number: null,
    paypal_email: null,
    invoice_currency: null,
    employee_type: "full_time",
    hourly_hours_source: null,
    payment_method: "bank",
    payment_account: "ES90 2100 0418 4502 0005 1332",
    department: "MyLinguaMeeting",
    job_title: "Coordinador",
    manager_id: null,
    hire_date: "2023-01-15",
    employment_status: "active",
    current_salary_amount: 62000,
    current_salary_currency: "USD",
    current_salary_effective_date: "2025-01-01",
    vacation_days_per_year: 20,
    vacation_days_used: 4,
    notes: null,
    created_by: null,
    updated_by: null,
    created_at: "2025-01-01T08:00:00Z",
    updated_at: "2025-01-01T08:00:00Z",
  },
  {
    id: "emp-2",
    employee_code: "0000000002",
    full_name: "Carlos Medina",
    first_name: "Carlos",
    last_name: "Medina",
    email: "carlos.medina@linguameeting.com",
    phone: "+1-555-0102",
    nationality: "MX",
    residence_country: "ES",
    legal_name_bank: null,
    identity_document: null,
    address_line: null,
    address_country: null,
    address_city: null,
    address_postal_code: null,
    bank_name: null,
    bank_account_number: null,
    swift_bic: null,
    bank_route_number: null,
    paypal_email: null,
    invoice_currency: "USD",
    employee_type: "full_time",
    hourly_hours_source: null,
    payment_method: "wise",
    payment_account: "wise-cmedina-001",
    department: "Finanzas",
    job_title: "Asistente",
    manager_id: "emp-1",
    hire_date: "2023-05-20",
    employment_status: "active",
    current_salary_amount: 52000,
    current_salary_currency: "USD",
    current_salary_effective_date: "2025-01-01",
    vacation_days_per_year: 18,
    vacation_days_used: 2,
    notes: null,
    created_by: null,
    updated_by: null,
    created_at: "2025-01-01T08:00:00Z",
    updated_at: "2025-01-01T08:00:00Z",
  },
];

export const mockSalaryHistory: SalaryHistory[] = [
  {
    id: "sal-1",
    employee_id: "emp-1",
    amount: 58000,
    currency: "USD",
    effective_date: "2024-01-01",
    reason: "Annual increase",
    created_by: null,
    created_at: "2024-01-01T12:00:00Z",
  },
  {
    id: "sal-2",
    employee_id: "emp-1",
    amount: 62000,
    currency: "USD",
    effective_date: "2025-01-01",
    reason: "Promotion adjustment",
    created_by: null,
    created_at: "2025-01-01T12:00:00Z",
  },
];

export const mockJobDepartmentHistory: JobDepartmentHistory[] = [
  {
    id: "job-1",
    employee_id: "emp-1",
    department: "MyLinguaMeeting",
    job_title: "Coordinador",
    effective_date: "2023-01-15",
    reason: "Initial assignment",
    created_by: null,
    created_at: "2023-01-15T12:00:00Z",
  },
  {
    id: "job-2",
    employee_id: "emp-2",
    department: "Finanzas",
    job_title: "Asistente",
    effective_date: "2023-05-20",
    reason: "Initial assignment",
    created_by: null,
    created_at: "2023-05-20T12:00:00Z",
  },
];

export const mockLoans: Loan[] = [
  {
    id: "loan-1",
    employee_id: "emp-2",
    description: "Emergency medical loan",
    principal_amount: 2400,
    currency: "USD",
    installments_total: 12,
    installments_paid: 3,
    installment_amount: 200,
    start_date: "2025-01-10",
    payroll_deduction_enabled: true,
    payroll_deduction_code: "PAYROLL-LOAN",
    outstanding_balance: 1800,
    status: "active",
    created_by: null,
    created_at: "2025-01-10T08:00:00Z",
    updated_at: "2025-03-01T08:00:00Z",
  },
];

export const mockLoanRepayments: LoanRepayment[] = [
  {
    id: "rep-1",
    loan_id: "loan-1",
    employee_id: "emp-2",
    amount: 200,
    paid_on: "2025-01-31",
    source: "payroll",
    payroll_period: "2025-01",
    note: "Payroll deduction",
    created_by: null,
    created_at: "2025-01-31T12:00:00Z",
  },
  {
    id: "rep-2",
    loan_id: "loan-1",
    employee_id: "emp-2",
    amount: 200,
    paid_on: "2025-02-28",
    source: "payroll",
    payroll_period: "2025-02",
    note: "Payroll deduction",
    created_by: null,
    created_at: "2025-02-28T12:00:00Z",
  },
  {
    id: "rep-3",
    loan_id: "loan-1",
    employee_id: "emp-2",
    amount: 200,
    paid_on: "2025-03-31",
    source: "payroll",
    payroll_period: "2025-03",
    note: "Payroll deduction",
    created_by: null,
    created_at: "2025-03-31T12:00:00Z",
  },
];

export const mockDashboardKpis: DashboardKpis = {
  totalEmployees: 2,
  activeEmployees: 2,
  openLoans: 1,
  pendingVacationRequests: 1,
  monthlyPayrollEstimate: 9500,
};
